# Generated by Django 4.0.1 on 2022-02-05 16:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_posting_last_modified'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SuperUser',
            new_name='User',
        ),
    ]
