# Generated by Django 4.0.1 on 2022-02-05 21:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0007_wallet_private_key"),
    ]

    operations = [
        migrations.RenameField(
            model_name="posting",
            old_name="cost",
            new_name="cost_per_day",
        ),
        migrations.CreateModel(
            name="Reservation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("starting_date", models.DateField()),
                ("end_date", models.DateField()),
                (
                    "total_cost",
                    models.DecimalField(decimal_places=2, default=0, max_digits=5),
                ),
                (
                    "asset",
                    models.ForeignKey(
                        default=None,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="api.asset",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        default=None,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="api.user",
                    ),
                ),
            ],
        ),
    ]
