# Generated by Django 4.0.1 on 2022-02-06 00:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_remove_reservation_asset_reservation_posting'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='last_modified',
            field=models.DateTimeField(blank=True, default=None),
        ),
    ]
