# Generated by Django 4.0.1 on 2022-03-05 21:24

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('description', models.CharField(max_length=255)),
                ('image_url', models.CharField(blank=True, default=None, max_length=1024, null=True)),
                ('rating', models.IntegerField(default=None, null=True, validators=[django.core.validators.MaxValueValidator(5), django.core.validators.MinValueValidator(1)])),
            ],
        ),
        migrations.CreateModel(
            name='Posting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20)),
                ('description', models.CharField(max_length=255)),
                ('available', models.BooleanField(default=True)),
                ('date_posted', models.DateTimeField(blank=True, default=None)),
                ('last_modified', models.DateTimeField(blank=True, default=None)),
                ('starting_date', models.DateField()),
                ('end_date', models.DateField()),
                ('cost_per_day', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('asset', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='api.asset')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=255)),
                ('rating', models.IntegerField(default=None, null=True, validators=[django.core.validators.MaxValueValidator(5), django.core.validators.MinValueValidator(1)])),
                ('picture_url', models.CharField(blank=True, default=None, max_length=1024, null=True)),
                ('password', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Wallet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('private_key', models.CharField(blank=True, default=None, max_length=255)),
                ('public_key', models.CharField(blank=True, default=None, max_length=255)),
                ('funds', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=5)),
                ('owner', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='api.user')),
            ],
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('starting_date', models.DateField()),
                ('end_date', models.DateField()),
                ('date_booked', models.DateTimeField(blank=True, default=None)),
                ('last_modified', models.DateTimeField(blank=True, default=None)),
                ('total_cost', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=5)),
                ('posting', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='api.posting')),
                ('user', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='api.user')),
            ],
        ),
        migrations.AddField(
            model_name='asset',
            name='owner',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='api.user'),
        ),
    ]
