# Generated by Django 4.0.1 on 2022-02-05 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_superuser_wallet_funds_wallet_public_key_posting_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='superuser',
            name='private_key',
            field=models.CharField(blank=True, default=None, max_length=255),
        ),
        migrations.AlterField(
            model_name='superuser',
            name='public_key',
            field=models.CharField(blank=True, default=None, max_length=255),
        ),
    ]
