# Generated by Django 4.0.1 on 2022-03-06 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_user_is_admin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wallet',
            name='funds',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10),
        ),
    ]
