# Generated by Django 4.0.1 on 2022-02-05 16:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_superuser_private_key_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='posting',
            name='owner',
        ),
        migrations.AddField(
            model_name='posting',
            name='asset',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='api.asset'),
        ),
        migrations.AlterField(
            model_name='posting',
            name='date_posted',
            field=models.DateTimeField(blank=True, default=None),
        ),
        migrations.AlterField(
            model_name='wallet',
            name='public_key',
            field=models.CharField(blank=True, default=None, max_length=255),
        ),
    ]
