# Generated by Django 4.0.1 on 2022-02-05 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_remove_posting_owner_posting_asset_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='posting',
            name='last_modified',
            field=models.DateTimeField(blank=True, default=None),
        ),
    ]
