# Generated by Django 4.0.1 on 2022-02-06 00:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_rename_cost_posting_cost_per_day_reservation'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='image_url',
            field=models.CharField(blank=True, default=None, max_length=1024, null=True),
        ),
        migrations.AddField(
            model_name='asset',
            name='rating',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='picture_url',
            field=models.CharField(blank=True, default=None, max_length=1024, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='rating',
            field=models.IntegerField(null=True),
        ),
    ]
