# Generated by Django 4.0.1 on 2022-02-06 00:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_reservation_booking_datetime_alter_asset_rating_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='total_cost',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AlterField(
            model_name='wallet',
            name='funds',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=5),
        ),
    ]
