# Generated by Django 4.0.1 on 2022-02-06 00:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_alter_reservation_total_cost_alter_wallet_funds'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reservation',
            old_name='booking_datetime',
            new_name='date_booked',
        ),
    ]
