# Generated by Django 4.0.1 on 2022-02-06 00:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_rename_booking_datetime_reservation_date_booked'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservation',
            name='asset',
        ),
        migrations.AddField(
            model_name='reservation',
            name='posting',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='api.posting'),
        ),
    ]
