# Generated by Django 4.0.1 on 2022-02-06 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_reservation_last_modified'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='private_key',
        ),
        migrations.RemoveField(
            model_name='user',
            name='public_key',
        ),
        migrations.AddField(
            model_name='posting',
            name='available',
            field=models.BooleanField(default=True),
        ),
    ]
